### ISSUE TITLE
convert tibble to data.frame 

### ISSUE THREAD

**Issue by waynelapierre** [sstoeckl/crypto2#12]
Thanks for this great R package! I used the crypto_history function to get all historical crypto prices from CoinMarketCap and got a tibble. When I convert this tibble to a data.frame, the resulted data.frame only has 11 rows. Not sure how this issue happened.

**Comment by sstoeckl** [comment]
Hi @waynelapierre. Please post your code following this guideline: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by waynelapierre** [comment]
require(crypto2)
all_crypto <- crypto_history()
all_crypto_df <- as.data.frame(all_crypto)

**Comment by sstoeckl** [comment]
It works for me. However, this code takes forever and I personally would try to be much more specific with regard to the data you want to download. E.g. start by only downloading active coins. Specify a date range. Nonetheless (due to another error mentioned in #13 and my fix in https://github.com/sstoeckl/crypto2/commit/d155ee0c1a1667a87d0a7a31a616a6339a1bd7d8 it should be running smoothly again.
