### ISSUE TITLE
Faster queries for short amount of data?

### ISSUE THREAD

**Issue by ekianjo** [sstoeckl/crypto2#7]
Hi, thanks for making this package, this is really useful.
I was trying out the crypto_history function and it seems that no matter if you put a short timeline to cover (just the past 7 days for example), it fetches the whole data anyway and executes a filter at the end. Would it be possible to fetch only the data of interest instead to make for much faster queries?
Thanks!

**Comment by sstoeckl** [comment]
Hi @ekianjo, I know from experience that - if properly - configured - crypto_history only fetches the timeframe desired (the entire dataset takes days to download). Could you post a MWE please, so that I could check what's happening?

**Comment by ekianjo** [comment]
Hi @sstoeckl  !
Here you go

end_date <- Sys.Date() -1
start_date <- Sys.Date() - 3
coins_history_latest <- crypto_history(coin_list =(crypto_list() %>% filter(symbol %in% c("BTC","ETH")) ),
                                end_date = end_date,start_date = start_date)

On my end it takes 40 seconds to run this query to return a dataframe that has 2 records only.

**Comment by sstoeckl** [comment]
Hi @ekianjo. 
`cl <- crypto_list()
end_date <- Sys.Date() -1
start_date <- Sys.Date() - 3
coins_history_latest <- crypto_history(coin_list =(cl %>% filter(symbol %in% c("BTC","ETH")) ),
                                       end_date = format(end_date,"%Y%m%d"),start_date = format(start_date,"%Y%m%d"),finalWait = FALSE)
`
If you run that code you will notice that the longest time is taken by `coin_list()` because that downloads information for approx 10'000 coins. Do that beforehand and you will realize that crypto_history is actually pretty fast AND it does not filter after downloading, ist does so before (faster download time). You can verify this when you check the latest version of the code on github.

**Comment by ekianjo** [comment]
thanks @sstoeckl actually coin_list is not the one that causes much delay (it runs actually very fast), but using the argument finalWait=False causes a major speedup - now the request runs in just in a matter of seconds! Thanks

**Comment by sstoeckl** [comment]
Just be aware, that `finalWait` is important when you run several requests in a row. If you do not wait 60s then it will just return the results from the last query.

**Comment by ekianjo** [comment]
@sstoeckl thanks for the info - so if requests are run with at least a few minutes in between is it safe to turn finalWait off?
